### ISSUE TITLE
[low-priority] WARN Meldungen beim Start / Überprüfung bungee.yml

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/LuckPermsNotifier#2]
```
[17:17:31] [main/WARN] [LuckPermsNotifier]: Plugin description config contains invalid property 'depend'!
[17:17:31] [main/INFO]: Loaded plugin LuckPermsNotifier version 1.0-SNAPSHOT by null
```

- Auto ist laut der Nachricht NULL
- Version ist laut der Nachricht 1.0
- Depend-Angabe gibt WARN aus

neu generierte bungee.yml Config sieht so aus und unterscheidet sich damit stark von aktuellen [in Github](https://github.com/RedstoneWorld/LuckPermsNotifier/blob/master/src/main/resources/bungee.yml).

```
depend:
- LuckPerms
authors:
- Phoenix616
commands:
  luckpermsnotifier:
    aliases:
    - lpn
    description: Main plugin command
    usage: 'Usage: /<command> [reload]'
    permission: luckpermsnotifier.command
    permission-message: You don't have the permission <permission>
```

_getestet mit LuckPermsNotifier #9 + Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:40370a3:388_
